apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer1
resources:
  - namespace.yaml
  - secrets.yaml
  - database.yaml
  - objectstore.yaml
  - scheduled-backup.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml
