apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

patches:
  - target:
      kind: SecretProviderClass
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "ac9bb7e1-d975-415c-aeae-1a0e7ba4e163"
      - op: replace
        path: /spec/parameters/keyvaultName
        value: "kv-mercury-prod"
      - op: replace
        path: /spec/parameters/tenantId
        value: "6c0d1498-a808-4d41-a865-fdebeb412738"

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
