apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "10ebab78-f6c8-4d5e-ac64-c0d85fb031d0"
      - op: replace
        path: /spec/parameters/tenantId
        value: "6c0d1498-a808-4d41-a865-fdebeb412738"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsstaging.blob.core.windows.net/customer1"
  - target:
      kind: Ingress
      name: customer1-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "customer1.mercury-staging.kubecraftlabs.com"
      - op: replace
        path: /spec/rules/0/host
        value: "customer1.mercury-staging.kubecraftlabs.com"
