apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - contact-points.yaml
  - notification-policies.yaml
  - n8n-alerts.yaml
  - database-alerts.yaml
  - cnpg-operator-alerts.yaml
  - node-alerts.yaml
  - pod-alerts.yaml
