apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer1-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - customer1.mercury.mischavandenburg.net
      secretName: customer1-tls
  rules:
    - host: customer1.mercury.mischavandenburg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer1-n8n
                port:
                  number: 3008
